#!/bin/bash
#PBS -N gibbs_abc_gpu
#PBS -l select=1:ncpus=16:mem=32gb:ngpus=1:gpu_type=L40S
#PBS -l walltime=0:15:00
#PBS -m abe
#PBS -k n
#PBS -j oe

module purge
module load tools/prod
module load Python/3.10.4-GCCcore-11.3.0

cd "$PBS_O_WORKDIR"

source venv/bin/activate

CONFIG_PATH="config.json"

RESULT_DIR=$(python3 -c "
from core.config import Config
cfg = Config('$CONFIG_PATH')
print(cfg.result_directory)")

mkdir -p "$RESULT_DIR"
rm -f "$RESULT_DIR/output_gpu.log" "$RESULT_DIR/error_gpu.log" "$RESULT_DIR/gibbs_abc_gpu.o*"

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export TORCH_NUM_THREADS=1
export N_WORKERS=16
export PARALLEL_BACKEND=thread

python rfp_gibbs_main.py > "$RESULT_DIR/output_gpu.log" 2> "$RESULT_DIR/error_gpu.log"

JOB_ID="${PBS_JOBID%%.*}"
DEFAULT_PBS_OUTPUT_FILE="$PBS_O_WORKDIR/gibbs_abc_gpu.o${JOB_ID}"
TARGET_PBS_OUTPUT_FILE="$RESULT_DIR/gibbs_abc_gpu.o${JOB_ID}"

if [ -f "$DEFAULT_PBS_OUTPUT_FILE" ]; then
    mv "$DEFAULT_PBS_OUTPUT_FILE" "$TARGET_PBS_OUTPUT_FILE"
fi