#!/bin/bash
#PBS -N gibbs_abc_gpu
#PBS -l select=1:ncpus=16:mem=32gb:ngpus=1:gpu_type=L40S
#PBS -l walltime=0:15:00
#PBS -m abe
#PBS -k n
#PBS -j oe

module purge
module load tools/prod
module load Python/3.10.4-GCCcore-11.3.0

cd "$PBS_O_WORKDIR"

rm -f output_gpu.log error_gpu.log
rm -f gibbs_abc_gpu.o*

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export TORCH_NUM_THREADS=1
export N_WORKERS=16
export PARALLEL_BACKEND=thread

source venv/bin/activate

exec > output_gpu.log 2> error_gpu.log

python rfp_gibbs_main.py configs/predict/deterministic-iterative-6h.json
